# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: d8322d5a72e31b00ad6f770f0995ba07c70eb1fdc1005e6d9d74fa89cd9660655de591c4a01b26f615a9feef0d75befd64298a27fa2de37007878745733de7ff
  twilio_account_sid: <%= ENV["TWILIO_ACCOUNT_SID"] %>
  twilio_auth_token: <%= ENV["TWILIO_AUTH_TOKEN"] %>
  twilio_number: <%= ENV["TWILIO_NUMBER"] %>
  s_publishable_key: <%= ENV["S_PUBLISHABLE_KEY"] %>
  s_secret_key: <%= ENV["S_SECRET_KEY"] %>

test:
  domain_name: example.com 
  secret_key_base: 84089d444666904a0f989ed7052ed6c87c3d82541e063eec244bc40e8add8c189bb1fab37ae5f541a0bfd23af0ff5a65cd33adf94546d5af8bcc236df0fea2ad
  twilio_account_sid: <%= ENV["TWILIO_ACCOUNT_SID"] %>
  twilio_auth_token: <%= ENV["TWILIO_AUTH_TOKEN"] %>
  twilio_number: <%= ENV["TWILIO_NUMBER"] %>
  s_publishable_key: <%= ENV["S_PUBLISHABLE_KEY"] %>
  s_secret_key: <%= ENV["S_SECRET_KEY"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twilio_account_sid: <%= ENV["TWILIO_ACCOUNT_SID"] %>
  twilio_auth_token: <%= ENV["TWILIO_AUTH_TOKEN"] %>
  twilio_number: <%= ENV["TWILIO_NUMBER"] %>
  s_publishable_key: <%= ENV["S_PUBLISHABLE_KEY"] %>
  s_secret_key: <%= ENV["S_SECRET_KEY"] %>
